self.addEventListener('push', function(event) {
    const options = {
        body: "This notification was generated by a push",
        icon: "images/logo.png",
        vibrate: [100, 50, 100],
        tag: 'push_notify',
        data: {
            dateOfArrival: Date.now(),
            primaryKey: '2'
        },
        actions: [
            { action: "explore", title: "Explore this new world", 
            icon: "images/checkmark.png" },
            {
                action: "close", title: "Close", icon: "images/xmark.png"
            }
        ]
    };
    event.waitUntil(self.registration.showNotification("The title from the server", options));
})